#!/bin/bash

# Function to display information about a subdomain
display_info() {
    domain=$1
    subdomain=$2
    dig_output=$(dig $subdomain.$domain | grep -A1 'ANSWER SECTION:')
    record_type=$(echo "$dig_output" | awk '{print $4}')
    destination=$(echo "$dig_output" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script
if [ $# -lt 1 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain=$1

if [ $# -eq 1 ]; then
    display_info $domain www
    display_info $domain lb-01
    display_info $domain web-01
    display_info $domain web-02
else
    subdomain=$2
    display_info $domain $subdomain
fi

