#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP header 'X-Served-By' with the hostname of the server

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to include custom header
HOSTNAME=$(hostname)
CONFIG_FILE="/etc/nginx/sites-available/default"

sudo sed -i '/server_name _;/a \\tadd_header X-Served-By '$HOSTNAME';' $CONFIG_FILE

# Restart Nginx to apply the changes
sudo systemctl restart nginx

echo "Nginx configured with custom header 'X-Served-By: $HOSTNAME'"

